version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./config/sa.json:/app/sa.json
      - ./config/.env:/app/.env